Repository SOPT-all/36-COLLABORATION-iOS-KB-STARBANKING, pull requests merged in 2025-05, with the labels that each got.

#4 [add] #3 Font 세팅
  KB-STARBANKING/KB-STARBANKING/Resource/Extension/UIFont+.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Font/Pretendard-Bold.otf
  KB-STARBANKING/KB-STARBANKING/Resource/Font/Pretendard-Light.otf
  KB-STARBANKING/KB-STARBANKING/Resource/Font/Pretendard-Medium.otf
  KB-STARBANKING/KB-STARBANKING/Resource/Font/Pretendard-Regular.otf
  KB-STARBANKING/KB-STARBANKING/Resource/Font/Pretendard-SemiBold.otf
  KB-STARBANKING/KB-STARBANKING/Resource/Info.plist
Labels: add, 세민

#5 [add] #2 Image&Icon 추가
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_down.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_down.imageset/ic_arrow_down.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_left.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_left.imageset/ic_arrow_left.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_right.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_right.imageset/ic_arrow_right.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_up.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_arrow_up.imageset/ic_arrow_up.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_close.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_close.imageset/ic_close.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_copy.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_copy.imageset/ic_copy.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_home.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_home.imageset/ic_home.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_menu.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_menu.imageset/ic_menu.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_menu_vert.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_menu_vert.imageset/ic_menu_vert.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_pencil.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_pencil.imageset/ic_pencil.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_plus.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_plus.imageset/ic_plus.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_scroll.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_scroll.imageset/ic_scroll.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_settings.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_settings.imageset/ic_settings.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_splits.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_splits.imageset/ic_splits.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_won.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ic/ic_won.imageset/ic_won.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_banner.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_banner.imageset/img_banner.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card1.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card1.imageset/img_card1.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card2.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card2.imageset/img_card2.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card3.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card3.imageset/img_card3.png
Labels: add, 현우

#6 [add] #1 Color 세팅
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Common/Black.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Common/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Common/White.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/GR1.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/GR2.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray1.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray2.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray3.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray4.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray5.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray6.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray7.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray8.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/GrayScale/Gray9.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Blue1.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Blue2.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Blue3.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Yellow1.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Yellow2.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/ColorStyles/Main/Yellow3.colorset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Extension/UIColor+.swift
Labels: add, 혜연

#14 [feat] #9 TotalAccountView 구현
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/AccountViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/Cell/AccountCell.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/TotalAccountViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/AddBankView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/BusinessAccountView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/SectionHeaderView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/TotalAccountHeaderView.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Extension/UIStackView+.swift
Labels: feat, 혜연

#15 [feat] #10 DetailView 구현
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/DetailViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/View/DetailAccountView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/View/DetailInfoView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/View/ManageAccountView.swift
Labels: feat, 혜연

#13 [feat] #7 InterestRateView 구현
  KB-STARBANKING/KB-STARBANKING/Application/SceneDelegate.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRateViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/RateCollection/RateData.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/RateCollection/RateViewCell.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/RateCollection/RateViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/View/BasicRateView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/View/InfoView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/View/PreferentialRateView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/View/preview.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard1.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard1.imageset/img_card1.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard2.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard2.imageset/img_card2.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard3.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/imgCard3.imageset/img_card3.png
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card1.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card2.imageset/Contents.json
  KB-STARBANKING/KB-STARBANKING/Resource/Assets.xcassets/img/img_card3.imageset/Contents.json
Labels: feat, 현우

#16 [feat] #8 TransactionView UI 구현
  KB-STARBANKING/KB-STARBANKING/Presentation/NavigationView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/TransactionViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/View/AccountInfo.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/View/PrimeRate.swift
Labels: feat, 세민

#18 [network] #17 네트워크 세팅
  KB-STARBANKING/KB-STARBANKING.xcodeproj/project.pbxproj
  KB-STARBANKING/KB-STARBANKING/Network/Base/BaseResponse.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/BaseService.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/Config.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/EndPoint.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/HeaderType.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/NetworkError.swift
  KB-STARBANKING/KB-STARBANKING/Network/Base/NetworkLogger.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Info.plist
Labels: 세민, network

#24 [hotfix] #23 BaseResponse 모델 정의 수정
  KB-STARBANKING/KB-STARBANKING/Network/Base/BaseResponse.swift
Labels: 세민, hotfix

#26 [network] #22 TotalAccountView API 연동
  KB-STARBANKING/KB-STARBANKING/Network/TotalAccount/TotalAccountResponse.swift
  KB-STARBANKING/KB-STARBANKING/Network/TotalAccount/TotalAccountService.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/Cell/AccountCell.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/TotalAccountViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/AccountView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/SectionHeaderView.swift
Labels: 혜연, network

#28 [network] #27 DetailView API 연동
  KB-STARBANKING/KB-STARBANKING/Network/Detail/DetailResponse.swift
  KB-STARBANKING/KB-STARBANKING/Network/Detail/DetailService.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/DetailViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/View/DetailAccountView.swift
Labels: 혜연, network

#29 [network] #25 InterestRateView API 연동
  KB-STARBANKING/KB-STARBANKING/Network/InterestRate/InterestRateResponse.swift
  KB-STARBANKING/KB-STARBANKING/Network/InterestRate/InterestRateService.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/Cell/RateViewCell.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/InterestRateViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/View/BasicRateView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/View/InfoView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/View/PreferentialRateView.swift
Labels: 현우, 세민, network

#30 [network] #21 TransactionView API 연동
  KB-STARBANKING/KB-STARBANKING/Network/Transaction/TransactionResponse.swift
  KB-STARBANKING/KB-STARBANKING/Network/Transaction/TransactionService.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/TransactionViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/View/AccountInfo.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/View/PrimeRate.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Extension/String+.swift
  KB-STARBANKING/KB-STARBANKING/Resource/Extension/UIFont+.swift
Labels: 세민, network

#32 [feat] #31 View 연결
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/DetailViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Detail/View/ManageAccountView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/InterestRate/InterestRateViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TopView/CloseHeaderView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TopView/NavigationView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/TotalAccountViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/TotalAccount/View/AccountView.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/TransactionViewController.swift
  KB-STARBANKING/KB-STARBANKING/Presentation/Transaction/View/AccountInfo.swift
Labels: feat, 세민
